# the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache.
networks:
  main:

services:
  webserver:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    networks:
      - main
    ports:
      - '4000:5000'
    depends_on:
      - prometheus
      - grafana
  
  apiserver:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    networks:
      - main
    ports:
      - '4001:5001'
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    networks:
      - main

# We can look at https://github.com/docker/awesome-compose if we want to integrate other services at some point and manage their deployment
# like MySQL, perhaps.