# the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache.
networks:
  main:

services:
  apiserver:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: minitwitapi
    networks:
      - main
    ports:
      - '4001:5001'
    command: ["app", "-env", "test"]

  webserver:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: minitwitclient
    networks:
      - main
    ports:
      - '4000:5000'
    depends_on:
      - apiserver
    command: ["app", "-env", "test"]

  webtests:
    build:
      context: .
      dockerfile: ./src-tests/Dockerfile
    networks:
      - main
    depends_on:
      - apiserver
      - webserver

# We can look at https://github.com/docker/awesome-compose if we want to integrate other services at some point and manage their deployment
# like MySQL, perhaps.