# the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache.
services:  
  apiserver:
    network_mode: "host"
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: ["app", "-env", "test"]

  apitests:
    network_mode: "host"
    build:
      context: .
      dockerfile: ./api-tests/Dockerfile
    depends_on:
      - apiserver
# We can look at https://github.com/docker/awesome-compose if we want to integrate other services at some point and manage their deployment
# like MySQL, perhaps.