# the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache.
services:  
  webserver:
    network_mode: "host"
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: ["app", "-env", "test"]

  webtests:
    network_mode: "host"
    build:
      context: .
      dockerfile: ./src-tests/Dockerfile
    depends_on:
      - webserver
# We can look at https://github.com/docker/awesome-compose if we want to integrate other services at some point and manage their deployment
# like MySQL, perhaps.