# the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache.
services:
  webserver:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: /usr/src/app/minitwit.db
        target: /root/minitwit/minitwit.db
  
  apiserver:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 5001:5001
    # We want to mount the database file to the container so that the data persists (mount from the VM to the container)
    volumes:
      - type: bind
        source: /usr/src/app/minitwit.db
        target: /root/minitwit/minitwit.db
# We can look at https://github.com/docker/awesome-compose if we want to integrate other services at some point and manage their deployment
# like MySQL, perhaps.