# the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache.
networks:
  main:

services:
  webserver:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: minitwit
    networks:
      - main
    ports:
      - '4000:5000'
    depends_on:
      - prometheus
      - grafana
      - loki
      - promtail
    command: ["app", "-env", "dev"]

  apiserver:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: minitwit_api
    networks:
      - main
    ports:
      - '4001:5001'
    depends_on:
      - prometheus
      - grafana
      - loki
      - promtail
    command: ["app", "-env", "dev"]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/config.yaml"
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/config.yaml
    networks:
      - main

  promtail:
    image: grafana/promtail:2.0.0 
    container_name: promtail
    volumes:
      - ./configs/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - ./log:/var/log  
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - main

  grafana:
    image: grafana/grafana:10.2.4
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - main

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yaml'
      - '--storage.path=/alertmanager'
    volumes:
      - ./configs/alertmanager.yaml:/etc/alertmanager/config.yaml
    ports:
      - 9093:9093
    networks:
      - main

volumes:
  grafana-storage: {}